[package]
name = "jsonsh"
version = "1.1.2"
edition = "2021"
description = "Process JSON/JSONC with JavaScript-like expressions (Rust port)"

[dependencies]
regex = { version = "1", default-features = false, features = [
    "std",
    "perf",
    "unicode-gencat",
    "unicode-script",
    "unicode-case",
    "unicode-perl",
] }
unicode-general-category = "1"

[lib]
name = "jsonsh"
path = "src/lib.rs"

[[bin]]
name = "jsonsh"
path = "src/main.rs"

[profile.release]
strip = true
lto = "fat"
codegen-units = 1
opt-level = "z"
panic = "abort"
